### ISSUE TITLE
Access to all options for Toastr

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/webnotifications#2]
Currently I can see no way of showing the progress bar on a timed message. In native toastr this would be done by setting the option progressBar = true.

Can the options argument for the component be extended to allow access to all the toastr native options?

**Comment by pruhsert** [comment]
You can pass in any option that the base library (toastr,js) supports like e.g.

plugins.webnotificationsToastr.success('message', 'title', {progressBar: true})

So any

toastr.options.xx

should be passed as {xx: y}

**Comment by pruhsert** [comment]
with 1.0.2 you can also set options globally...

**Comment by SteveHawes** [comment]
Hi Patrick,

 

It looks like you need to update the version number in the manifest file. I have installed the latest release but it still thinks I have 1.0.1 and that there is an update available.

 

Thanks

Steve

 

 

 

Web:     www.elysiumwebservices.com

Tel:         (+34) 681 25 95 32

**Comment by pruhsert** [comment]
done that, thanks
