### ISSUE TITLE
Options appear to be ignored if title is not set

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/webnotifications#3]
I have tried to use the following call to display a progress bar as suggested in Issue #2 :-

`plugins.webnotificationsToastr.success('message', 'title', {progressBar: true})`

and this works fine but if I do not want a title to be shown and instead use the code:

`plugins.webnotificationsToastr.success('message', null, {progressBar: true});`
or
`plugins.webnotificationsToastr.success('message', '', {progressBar: true});`

the additional options appear to be ignored and the default ones are used.

How can I set the additional options without requiring a title to be displayed?

Thanks
Steve

**Comment by SteveHawes** [comment]
It also appears that the title and the message are reversed when being displayed.
![toastr](https://cloud.githubusercontent.com/assets/23415735/20812392/495e5f72-b809-11e6-83b4-2f98dd02ad2f.png)

**Comment by pruhsert** [comment]
This

`plugins.webnotificationsToastr.success('message', '', {progressBar: true});`

should work now as expected
