### ISSUE TITLE
error in reading spec file in servoy for version 1.2.0

### ISSUE THREAD

**Issue by tp-pitc** [Servoy/webnotifications#8]
Error message: could not read specification files content of toastr/toastr.spec, url is not resolved, casing problem?
Error message: could not read specification files content of webNotifications/webNotifications.spec, url is not resolved, casing problem?
Using Servoy 2021.09.3701
I have to down grade to 1.1.3 for no errors

**Comment by meraedit** [comment]
fixed and released version 1.2.1
